backend/modules/cms/controllers/PageController.php
<?php

namespace backend\modules\cms\controllers;

use backend\modules\cms\Cms;
use common\widgets\Alert;
use backend\modules\cms\models\Page;
use backend\modules\cms\models\PageSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class PageController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],

                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(
            'index',
            [
                'dataProvider' => $dataProvider,
            ]
        );
    }

    /**
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Page();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Alert::add(Cms::t('msg', 'Operation completed successfully.'), Alert::TYPE_SUCCESS);

            if (isset($_POST['apply'])) {
                return $this->redirect(['update', 'id' => $model->id]);
            }

            return $this->redirect(['index']);

        } else {

            return $this->render(
                'create',
                [
                    'model' => $model,
                ]
            );
        }
    }

    /**
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Alert::add(Cms::t('msg', 'Operation completed successfully.'), Alert::TYPE_SUCCESS);

            if (isset($_POST['apply'])) {
                return $this->redirect(['update', 'id' => $model->id]);
            }

            return $this->redirect(['index']);

        } else {
            return $this->render(
                'update',
                [
                    'model' => $model,
                ]
            );
        }
    }

    public function actionPosition($id, $position)
    {
        if ($model = Page::findOne($id)) {
            $model->position = $position;
            $model->update(false);
            Page::reSortPosition($model->language);
        }

        return $this->redirect(['index']);
    }

    /**
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if ($this->findModel($id)->childs) {
            Alert::add(Cms::t('msg', 'First delete all childs'), Alert::TYPE_SUCCESS);
        } else {
            $this->findModel($id)->delete();
            Alert::add(Cms::t('msg', 'Operation completed successfully.'), Alert::TYPE_SUCCESS);
        }

        return $this->redirect(['index']);
    }

    /**
     * @param string $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/cms/views/page/_form.php
<?php

use dosamigos\tinymce\TinyMceAsset;
use kartik\widgets\SwitchInput;
use backend\modules\cms\Cms;
use backend\modules\cms\models\I18n;
use backend\modules\cms\models\Page;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->registerJs(
    <<<'JS'
    tinymce_settings = {
    selector: 'page-content',
    height: 500,
    width:'100%',
    statusbar: true,
    convert_urls: false,
    valid_children: '+body[style]',
    plugins: [
        "advlist autolink lists link charmap print preview anchor", 
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste image"
    ],
    toolbar: 'undo redo | styleselect | bold italic | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link code',
  };

   toggle_value=0;
    function editorToggle()
    {
        if(toggle_value) {
            var editor = tinymce.EditorManager.get('page-content').remove();
            toggle_value =0;
        } else {
            var editor = tinymce.EditorManager.createEditor('page-content',tinymce_settings).render();
            toggle_value =1;
        }
    }
JS
);
?>
<?php TinyMceAsset::register($this); ?>

<div class="pages-form box-body">
    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-sm-3">
            <?= $form->field($model, 'language')->dropDownList(I18n::getLanguages()) ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'parent_id')->dropDownList(Page::getFilter(), ['prompt' => Cms::t('lbl', 'Main menu')]) ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'position')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'active')->dropDownList([1 => Cms::t('lbl', 'Yes'), 0 => Cms::t('lbl', 'No')]) ?>
        </div>
    </div>
    <?= $form->field($model, 'title')->textInput(['maxlength' => true, 'autofocus' => true]); ?>
    <?= $form->field($model, 'content')->textarea(['rows' => 15]); ?>

    <label class="control-label"><?= Cms::t('lbl', 'WYSWIG Editor'); ?></label>
    <?= SwitchInput::widget(
        [
            'name' => 'editor_switch',
            'value' => false,
            'id' => 'editor_switch',
            'pluginEvents' => ["switchChange.bootstrapSwitch" => "function() { editorToggle(); }"],
        ]
    ); ?>

    <div class="row">
        <div class="col-sm-3">
            <?= $form->field($model, 'type_id')->dropDownList(Page::getTypes()) ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'template')->dropDownList(Page::getTemplates()) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($model, 'link')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <?= $form->field($model, 'meta_title')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'meta_desc')->textInput(['maxlength' => true]) ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Cms::t('lbl', 'Create') : Cms::t('lbl', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::submitButton(Cms::t('btn', 'Apply'), ['class' => 'btn btn-default', 'name' => 'apply']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/modules/cms/views/page/create.php
<?php

use backend\modules\cms\Cms;

$this->title = Cms::t('lbl', 'Create page');
$this->params['breadcrumbs'][] = ['label' => Cms::t('lbl', 'Pages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="pages-create col-xs-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
            </div>
        </div>
    </div>
</div>

backend/modules/cms/views/page/index.php
<?php

use leandrogehlen\treegrid\TreeGrid;
use backend\modules\cms\Cms;
use yii\helpers\Html;

$this->title = Cms::t('lbl', 'Pages');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <?= Html::a(Cms::t('btn', 'Create page'), ['create'], ['class' => 'btn btn-success pull-right btn-sm']) ?>
            </div>
            <div class="panel-body">
                <?= TreeGrid::widget([
                    'dataProvider' => $dataProvider,
                    'keyColumnName' => 'id',
                    'parentColumnName' => 'parent_id',
                    'parentRootValue' => 0,
                    'columns' => [
                        [
                            'header' => Cms::t('lbl', 'Type'),
                            'format' => 'raw',
                            'value' => function ($model) {
                                $out = Html::a('<i class="glyphicon glyphicon-arrow-up"></i>', ['page/position', 'id' => $model->id, 'position' => ($model->position - 3)]);
                                $out .= Html::a('<i class="glyphicon glyphicon-arrow-down"></i>', ['page/position', 'id' => $model->id, 'position' => ($model->position + 3)]);

                                return $out;
                            },
                        ],
                        'position',
                        'title',
                        [
                            'header' => Cms::t('lbl', 'Type'),
                            'attribute' => 'type_id',
                            'value' => function ($model) {
                                return $model->type;
                            },
                        ],
                        [
                            'header' => Cms::t('lbl', 'Template'),
                            'attribute' => 'template',
                            'value' => function ($model) {
                                return $model->getTemplate();
                            },
                        ],
                        [
                            'header' => Cms::t('lbl', 'Link'),
                            'attribute' => 'link',
                            'value' => function ($model) {
                                return $model->getLink();
                            },
                        ],
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{update} {delete}',
                            'headerOptions' => ['width' => 70],
                        ],
                    ],
                ]); ?>
            </div>
        </div>
    </div>
</div>

backend/modules/cms/views/page/update.php
<?php

use backend\modules\cms\Cms;

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Cms::t('lbl', 'Pages'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Cms::t('lbl', 'Update');
?>

<div class="row">
    <div class="pages-update col-xs-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <?= $this->render('_form', [
                    'model' => $model,
                ]) ?>
            </div>
        </div>
    </div>
</div>