common/models/Client.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\helpers\ArrayHelper;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "client".
 *
 * @property string $id
 * @property string $login
 * @property string $date
 * @property integer $fv
 * @property string $fv_nip
 * @property string $fv_company
 * @property string $fv_address
 * @property string $fv_postcode
 * @property string $fv_city
 * @property string $fv_country
 * @property string $d_company
 * @property string $d_name
 * @property string $d_address
 * @property string $d_postcode
 * @property string $d_city
 * @property string $d_country
 * @property string $d_phone
 * @property string $c_name
 * @property string $c_email
 * @property string $c_phone
 * @property string $password
 * @property integer $rabat
 */
class Client extends \yii\db\ActiveRecord implements IdentityInterface {

    const SCENARIO_REGISTER = 'register';
    const SCENARIO_NO_ACCOUNT = 'no-account';

    var $passwordNew, $passwordConfirm;
    var $term1, $term2, $newsletter;
    var $deliveryCopyFromClient;
    var $fvCopyFromClient;
    var $fvCopyFromDelivery;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'client';
    }

    /**
     * __toString()
     *
     * @return string
     */
    public function __toString() {
        return $this->c_name;
    }

    public function getToString() {
        return $this->c_name;
    }

    public static function getFilterList() {
        return ArrayHelper::map(self::find()->asArray()->all(), 'id', 'id');
    }

    public static function isPasswordResetTokenValid($token) {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];

        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['auth_key'], 'string', 'max' => 32],
            [['date'], 'safe'],
            [['d_name', 'd_address', 'd_postcode', 'd_city', 'd_country', 'd_phone', 'd_email',
            'c_name', 'c_email', 'c_phone', 'c_address', 'c_country', 'c_postcode', 'c_city'], 'required'],
            [['fv', 'rabat', 'newsletter'], 'integer'],
            [
                ['c_email'],
                function ($attr) {
            if (Client::find()->andWhere(['c_email' => $this->c_email])->andWhere(['is not', 'password', null])->limit(1)->one()) {
                $this->addError('c_email', 'Na podany adres email zostało już założone konto');
            }
        },
                'on' => self::SCENARIO_REGISTER
            ],
            [['c_email'], 'email'],
            [['login', 'passwordNew', 'passwordConfirm'], 'string', 'max' => 100],
            [['fv_nip'], 'string', 'max' => 13],
            [['fv_company', 'fv_address', 'fv_city', 'fv_country', 'd_company', 'd_name', 'd_address', 'd_city', 'd_country', 'd_phone', 'c_name', 'c_email', 'c_phone'], 'string', 'max' => 255],
            [['fv_postcode', 'd_postcode'], 'string', 'max' => 6],
            [['password'], 'string', 'max' => 32],
            [['passwordNew', 'passwordConfirm'], 'required', 'on' => self::SCENARIO_REGISTER],
            [['term1', 'term2'], 'required'],
            ['term1', 'required', 'requiredValue' => 1, 'message' => 'Musisz zaakceptowac regulamin'],
            ['term2', 'required', 'requiredValue' => 1, 'message' => 'Musisz zaakceptowac zgodę na przetwarzanie danych'],
        ];
    }

    public function scenarios() {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_NO_ACCOUNT] = ['d_postcode', 'fv_company', 'fv_address', 'fv_city', 'fv_country', 'd_company', 'd_name', 'd_address', 'd_city', 'd_country', 'd_phone', 'c_name', 'c_email', 'c_phone', 'term1', 'term2'];
        return $scenarios;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'login' => Yii::t('app', 'Login'),
            'date' => Yii::t('app', 'Data rejestracji'),
            'fv' => Yii::t('app', 'Proszę o dostarczenie faktury VAT'),
            'fv_nip' => Yii::t('app', ' Nip'),
            'fv_company' => Yii::t('app', 'Firma'),
            'fv_address' => Yii::t('app', 'Ulica nr'),
            'fv_postcode' => Yii::t('app', 'Kod pocztowy'),
            'fv_city' => Yii::t('app', 'Miejscowość'),
            'fv_country' => Yii::t('app', 'Kraj'),
            'd_company' => Yii::t('app', 'Firma'),
            'd_name' => Yii::t('app', 'Imię i nazwisko'),
            'd_address' => Yii::t('app', 'Ulica nr'),
            'c_address' => Yii::t('app', 'Ulica nr'),
            'd_postcode' => Yii::t('app', 'Kod pocztowy'),
            'c_postcode' => Yii::t('app', 'Kod pocztowy'),
            'd_city' => Yii::t('app', 'Miejscowość'),
            'c_city' => Yii::t('app', 'Miejscowość'),
            'd_country' => Yii::t('app', 'Kraj'),
            'c_country' => Yii::t('app', 'Kraj'),
            'd_phone' => Yii::t('app', 'Telefon'),
            'c_name' => Yii::t('app', 'Imię i nazwisko'),
            'c_email' => $this->scenario == self::SCENARIO_REGISTER ? Yii::t('app', 'Login / Email') : 'Email',
            'd_email' => 'Email',
            'c_phone' => Yii::t('app', 'Telefon'),
            'password' => Yii::t('app', 'Hasło'),
            'rabat' => Yii::t('app', 'Rabat'),
            'passwordNew' => 'Hasło',
            'passwordConfirm' => 'Potwierdź hasło',
            'term1' => 'Akceptacja regulaminu',
            'term2' => 'Zgoda na przetwarzanie danych',
            'newsletter' => 'Zgodna na newsletter',
            'deliveryCopyFromClient' => 'użyj danych z danych zamawiającego',
            'fvCopyFromClient' => 'użyj danych z danych zamawiającego',
            'fvCopyFromDelivery' => 'użyj danych z danych do wysyłki',
        ];
    }

    public function sendConfirmMail() {
//        $state = Yii::$app->setting->mailer()->compose('confirm-mail', ['model' => $this])
//                ->setTo($this->c_email)
//                ->setFrom([Yii::$app->setting->get('smtp_login') => $_SERVER['HTTP_HOST']])
//                ->setSubject('Rejestracja w serwisie')
//                ->send();
        $state = Yii::$app->mailer->compose('confirm-mail', [ 'model' => $this])
                ->setTo($this->c_email)
                ->setFrom([Yii::$app->params['adminEmail'] => $_SERVER['HTTP_HOST']])
                ->setSubject('Rejestracja w serwisie')
                ->send();
        //var_dump($state);
        //exit(0);

        if ($state) {
            return true;
        } else {
            return false;
        }
    }

    public function sendResetEmail() {
        $link = 'http://' . $_SERVER['HTTP_HOST'] . '/panel/users/reset?token=' . $this->password_reset_token;
//        $state = Settings::mailer()->compose('reset-password', ['link' => $link])
//                ->setTo($this->email)
//                ->setFrom([Settings::g('smtp_login', 'form') => $_SERVER['HTTP_HOST']])
//                ->setSubject(Yii::t('app', 'Reset Password'))
//                ->send();
        $state = Yii::$app->mailer->compose('reset-password', ['link' => $link])
                ->setTo($this->email)
                ->setFrom([Yii::$app->params['adminEmail'] => $_SERVER['HTTP_HOST']])
                ->setSubject(Yii::t('app', 'Reset Password'))
                ->send();
        if ($state) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id) {

        return static::findOne(['id' => $id, 'active' => 1]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null) {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username) {
        return static::find()->andWhere(['c_email' => $username, 'active' => 1])->andWhere(['is not', 'password', null])->limit(1)->one();
    }

    public function getId() {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey() {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey) {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password) {
        return md5($password) == $this->password;
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey() {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken() {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken() {
        $this->password_reset_token = null;
    }

    public function setPassword($password) {
        $this->password = md5($password);
    }

}

backend/views/layouts/_about.php
<?php 
use app\modules\cms\models\Box;
$box = Box::forceGet('about'); ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="img-noborder">
                <?php echo $box['content']; ?>
            </div>
        </div>
    </div>
</div>

backend/views/layouts/_copyright.php
<?php 
use bizley\cookiemonster\CookieMonster;
?>
<div class="container">
    <div class="row">
        <div class="clear20"></div>
        <div class="col-md-6 text-left">
            Copyright <?= date("Y"); ?> Tanie Torebki. All right reserved
        </div>
        <div class="col-md-6 text-right">
            Projektowanie zaawansowanych sklepów internetowych <a href="http://guido.com.pl">GUIDO</a>
        </div>
    </div>
</div>

<div class="clear20"></div>
<span id="toTop" onclick="$('html, body').animate({scrollTop: 0}, 200);"></span>
<?php $this->registerJs('
  $(window).scroll(function(){
     if( $(window).scrollTop() > 100 ) 
      $("#toTop").show();
      else
      $("#toTop").hide();
    });
'); ?>

<?php $this->registerJs(
  "$(document).delegate('*[data-toggle=\"lightbox\"]', 'click', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    }); "
); ?>

<?= CookieMonster::widget([
    'content' => [
        'buttonMessage' => 'OK', // instead of default 'I understand'
        'mainMessage' => 'Strona korzysta z plików cookies w celu realizacji usług i zgodnie z Polityką Plików Cookies. Możesz określić warunki przechowywania lub dostępu do plików cookies w Twojej przeglądarce.'
    ],
    'mode' => 'bottom'
])?>

<?php $this->endBody() ?>

<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 882229760;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt=""
          src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/882229760/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

backend/views/layouts/_facebook.php
<div class="col-lg-6 facebook text-center">
    <div class="fb-page" data-href="https://www.facebook.com/tanietorebki.compl/" data-width="500" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"></div>

    <div id="fb-root"></div>
    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id))
                return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.7&appId=1434596460171508";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
</div>

backend/views/layouts/_four_boxes.php
<?php
use app\modules\cms\models\Box;
use yii\helpers\Html;
$countBox=3;
?>
<div class="container start-box">
    <div class="row">
        <?php for ($i = 1; $i <= $countBox; $i++): ?>
            <div class="col-md-<?= (int)12/$countBox ?> col-sm-6 col-xs-12 static-box-rwd">
                <?php $box = Box::forceGet('home' . $i, 100) ?>
                <div class="box box-<?php echo $i; ?>">
                    <?php
                        $content = Html::img('/images/smallbaner' . $i . '.png', ['class' => 'img-responsive', 'style'=>"width:100%", 'alt' => $box['title']]);
                        echo Html::a($content, $box['link']); ?>
                    
                    <div class="desc">
                        <?= $box['content']; ?>
                    </div>
                </div>
            </div>
        <?php endfor; ?>
    </div>
</div>

backend/views/layouts/_head.php
<?php 
use yii\helpers\Html;
 ?>
<meta charset="<?= Yii::$app->charset ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?= Html::csrfMetaTags() ?>
<title><?= Html::encode($this->title) ?></title>

<meta name="google-site-verification" content="z_IjrKFw3PGvsWQsAP6MLDNpqkH0-mBkKx3OCsW6gmY"/>
<meta name="google-site-verification" content="t2pFXmSimOABNTUO6N_J-44uXHjRgwcsJ9y9E9Rdfn0" />

<?php $this->head() ?>
<script>
  (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
          (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
              m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
  })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
  ga('create', 'UA-77755729-1', 'auto');
  ga('send', 'pageview');
</script>

backend/views/layouts/_logos.php
<div class="container">
    <div class="image-bar">
        <img src="/img/logo_intel.png" class="img-responsive"/>
        <img src="/img/logo_lenovo.png" class="img-responsive"/>
        <img src="/img/logo_linux.png" class="img-responsive"/>
        <img src="/img/logo_obm.png" class="img-responsive"/>
        <img src="/img/logo_fujitsu.png" class="img-responsive"/>
        <img src="/img/logo_hp.png" class="img-responsive"/>
        <img src="/img/logo_microsoft.png" class="img-responsive"/>
        <img src="/img/logo_dell.png" class="img-responsive"/>
    </div>
</div>

backend/views/layouts/_nav.php
<?php 
use yii\helpers\Html;
use app\models\Category;
use app\models\Basket;
use yii\helpers\Url;
?>


<div class="container">
    <div class="row">
        <div class="col-md-3">
            <a href="/"><?= Html::img('/images/logo.png', ['class' => 'img-responsive logo']); ?></a>
        </div>
        <div class="col-md-5">
            <form id="searchBar" class="search-bar-wrapper" method="get" action="<?= Url::to(['product/search']); ?>">
                <div class="search-bar">
                    <div class="search-text">
                        <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>"/>
                        <input type="text" autocomplete="off" value="" name="ProductSearch[name]" placeholder="Szukana fraza">
                    </div>
                    <div class="search-groups visible-lg visible-md">
                        <select name="ProductSearch[category_id]">
                            <option value="">wszystkie</option>
                            <?php foreach (Category::getMain() as $category): ?>
                                <option value="<?= $category->id; ?>"><?= $category->title; ?></option>
                                <?php $childs = $category->getChildLimit(21)->all(); ?>
                                <?php foreach ($childs as $child): ?>
                                    <option value="<?= $child->id; ?>"> -- <?= $child->title; ?></option>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="search-button">
                        <button class="btn btn-success btn-orange" type="submit">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </form>

        </div>
        <div class="col-md-4">
            <div class="bars">
                <div class="phone menu-bars text-center">
                    <a href="<?= Url::to(['site/contact']); ?>">
                        <i class="glyphicon glyphicon-envelope text-gray" style="color: #B2B2B2; font-size: 24pt;" aria-hidden="true"></i>
                        <br />
                        <span style="color: #2D2D2D;">
                            <?= Yii::t('app', 'Napisz do nas') ?>
                        </span>
                    </a>
                </div>
                <div class="user text-center menu-bars">
                    <a href="<?= Url::to(['client/profile']); ?>">
                        <?= Html::img('@web/images/user.png', ['class' => 'img-responsive']); ?>
                        <span>Twój profil</span>
                        <?php if (!Yii::$app->user->isGuest): ?>
                            <?= Yii::$app->user->identity->toString ?>
                        <?php endif; ?>
                    </a>
                </div>
                <div class="cart text-center menu-bars">
                    <a href="<?= Url::to(['shop/card']); ?>" id="basket-ico">
                        <?= Html::img('@web/images/cart.png', ['class' => 'img-responsive']); ?>
                        <?php if ($count = Basket::scount()): ?>
                            <span class="badge badge-danger"><?= $count; ?></span>
                        <?php endif; ?>
                        <span>Koszyk</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/layouts/_navbar.php
<?php 

use yii\helpers\Html;
use app\models\Category;
?>
<div class="navbar yamm"><div class="container">

  <div class="navbar-header visible-xs visible-sm">
      <button type="button" data-toggle="collapse" data-target="#navbar-collapse-1" class="navbar-toggle">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
  </div>

  <div id="navbar-collapse-1" class="navbar-collapse collapse padding-0">
      <ul class="nav navbar-nav">
          <?php foreach (Category::getMain() as $category): ?>
<li>
<?= Html::a(
    Html::img('/images/category_' . $category->slug . '.png', ['class' => '']) .  $category->title,
    ['product/index', 'id' => $category->id, 'slug' => $category->slug],
    ['style' => 'todo', 'aria-expanded' => "false"])
?>
</li>
              <?php endforeach; ?>
      </ul>
  </div>

</div></div>

backend/views/layouts/_newsletter_section.php
  <div class="container">
      <div class="row" style="padding-top: 40px; padding-bottom: 40px;">
          <div class="col-sm-4">
              <form action="/newsletter/subscribe" method="post">
                  <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>"/>
                  <h4 class="beauty">Newsletter</h4>
                  <hr class="header-delimiter"/>
                  Dowiedz się o różnych ofertach i promocjach!
                  <div class="input-group">
                      <input type="text" class="form-control email-input" placeholder="Adres e-mail" name="NewsletterEmail[mail]"/>
                      <span class="input-group-btn">
                          <button class="btn btn-primary email-button" type="submit">Wyślij!</button>
                      </span>
                  </div>
                  <div class="checkbox">
                      <label><input type="checkbox" name="NewsletterEmail[terms]">Akceptuję regulamin</label>
                  </div>
              </form>
          </div>

          <div class="col-sm-8 our-adventages">
              <h4 class="beauty">Nasze atuty</h4>
              <hr class="header-delimiter"/>
              <div class="col-sm-4">
                  <span><img src="/images/fast_delivery.png"/></span>
                  <span class="caption"> <b style="display: block">Szybka<br>dostawa</b></span>
              </div>
              <div class="col-sm-4">
                  <span> <img src="/images/calendar.png"/></span>
                  <span class="caption"> <b style="display: block">14 dni <br>na zwrot</b></span>
              </div>
              <div class="col-sm-4">
                  <span> <img src="/images/secure_payments.png"/></span>
                  <span class="caption"> <b style="display: block">Bezpieczne <br>płatności</b></span>
              </div>
          </div>
      </div>
  </div>

backend/views/layouts/image_bar.php
<div class="container">
  <div class="image-bar">
      <img src="/img/layer_20.png" class="img-responsive"/>
  </div>
</div>

backend/views/layouts/main_delete.php
<?php

use app\models\Category;
use app\models\Basket;
use app\themes\sportstyle\assets\AppAsset;
use raoul2000\bootswatch\BootswatchAsset;
use yii\helpers\Html;

BootswatchAsset::$theme = 'readable';
AppAsset::register($this);
$baseUrl = $this->baseUrl;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <title><?= Html::encode($this->title) ?></title> 
        <?php $this->head() ?>

    </head>
    <body>
        <?php $this->beginBody() ?>
        <!-- Navigation -->
        <div class="container">

            <!-- Heading Row -->
            <div class="row">
                <div class="col-md-4">
                    <a href="/"><?= Html::img('@web/images/logo.jpg', ['class' => 'img-responsive logo']); ?></a>
                </div>
                <div class="col-md-4">

                    <form id="searchBar" class="search-bar-wrapper" method="get" action="/szukaj">
                        <div class="search-bar">
                            <div class="search-text">
                                <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>"/>
                                <input type="text" autocomplete="off" value="" name="ProductSearch[name]" placeholder="Szukana fraza">
                            </div>
                            <div class="search-groups visible-lg visible-md">
                                <select name="ProductSearch[category_id]">
                                    <option value="">wszystkie</option>
                                    <?php foreach (Category::getMain() as $category): ?>
                                        <option value="<?= $category->id; ?>"><?= $category->title; ?></option>
                                        <?php $childs = $category->getChildLimit(21)->all(); ?>
                                        <?php foreach ($childs as $child): ?>
                                            <option value="<?= $child->id; ?>"> -- <?= $child->title; ?></option>
                                        <?php endforeach; ?>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="search-button">
                                <button class="button" type="submit"><i class="fontello icon-search"></i></button>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="col-md-4">
                    <div class="bars">
                        <div class="phone menu-bars ">
                            + 48 32 270 24 15<br>
                            <a href="/pl/page/kontakt">Napisz do nas</a>
                        </div>
                        <div class="user text-center menu-bars">
                            <a href="/client/profile">
                                <?= Html::img('@web/images/user.png', ['class' => 'img-responsive']); ?>
                                <span>Twój profil</span>
                                <?php if (!Yii::$app->user->isGuest): ?>
                                    <?= Yii::$app->user->identity->toString ?>
                                <?php endif; ?>
                            </a>
                        </div>
                        <div class="cart text-center menu-bars">
                            <a href="/shop/card" id="basket-ico">
                                <?= Html::img('@web/images/cart.png', ['class' => 'img-responsive']); ?>
                                <?php if ($count = Basket::scount()): ?>
                                    <span class="badge badge-danger"><?= $count; ?></span>
                                <?php endif; ?>
                                <span>Koszyk</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="http://placehold.it/150x50&text=Logo" alt="">
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#">About</a>
                        </li>
                        <li>
                            <a href="#">Services</a>
                        </li>
                        <li>
                            <a href="#">Contact</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <!-- Page Content -->
        <div class="container">

            <!-- Heading Row -->
            <div class="row">
                <div class="col-md-8">
                    <img class="img-responsive img-rounded" src="http://placehold.it/900x350" alt="">
                </div>
                <!-- /.col-md-8 -->
                <div class="col-md-4">
                    <h1>Business Name or Tagline</h1>
                    <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
                    <a class="btn btn-primary btn-lg" href="#">Call to Action!</a>
                </div>
                <!-- /.col-md-4 -->
            </div>
            <!-- /.row -->

            <hr>

            <!-- Call to Action Well -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="well text-center">
                        This is a well that is a great spot for a business tagline or phone number for easy access!
                    </div>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->

            <!-- Content Row -->
            <div class="row">
                <div class="col-md-4">
                    <h2>Heading 1</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
                    <a class="btn btn-default" href="#">More Info</a>
                </div>
                <!-- /.col-md-4 -->
                <div class="col-md-4">
                    <h2>Heading 2</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
                    <a class="btn btn-default" href="#">More Info</a>
                </div>
                <!-- /.col-md-4 -->
                <div class="col-md-4">
                    <h2>Heading 3</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
                    <a class="btn btn-default" href="#">More Info</a>
                </div>
                <!-- /.col-md-4 -->
            </div>
            <!-- /.row -->

            <!-- Footer -->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Copyright &copy; Your Website 2014</p>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.container -->
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>